[package]
name = "clemento-lang"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
thiserror = "2.0.17"
